# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
required = ["github.com/laher/goxc", "github.com/inconshreveable/mousetrap"]



[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/olekukonko/tablewriter"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[prune]
  go-tests = true
  unused-packages = true
